[package]
name = "web-server-test"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.2"
actix-web = "4.3.0"
rusqlite = "0.28.0"
sailfish = "0.6.0"
serde = { version = "1.0.152", features = ["derive"] }
